DELETE http://localhost:3001/api/blogs/604cb74cb5b6e02e98576c2b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MDRiNGVmYmEwYTA1ZjEwNzA5MzcxYzgiLCJpYXQiOjE2MTU2NDMwNTUsImV4cCI6MTYxNTY0NjY1NX0.0aGEblNV24igEDA85MU9RpKWnLNwNZM1j_14ew0EwFE